services:
  app:
    build: .
    container_name: cubify_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ./mvnw spring-boot:run
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: cubify_db
    environment:
      POSTGRES_DB: cubify
      POSTGRES_USER: cubify_user
      POSTGRES_PASSWORD: cubipassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: